<?php 
	$_helper_store = $this->helper('StudioEmma\Core\Helper\Store');
?>
<meta property="og:locale" content="<?php echo $_helper_store->getLocale()?>" />
<meta property="og:type" content="og:product" />
<meta property="og:title" content="<?php echo $block->stripTags($block->getProduct()->getName()); ?>" />
<meta property="og:image" content="<?php echo $block->stripTags($block->getImage($block->getProduct(), 'product_base_image')->getImageUrl()); ?>" />
<meta property="og:description" content="<?php echo $block->stripTags($block->getProduct()->getShortDescription()); ?>" />
<meta property="og:url" content="<?php echo $block->stripTags($block->getProduct()->getProductUrl()); ?>" />
<?php if ($priceAmount = $block->getProduct()->getFinalPrice()):?>
    <meta property="product:price:amount" content="<?php echo $priceAmount; ?>"/>
    <?php echo $block->getChildHtml('meta.currency'); ?>
<?php endif;?>
