<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $block->getViewFileUrl('Magento_Theme::images/icons/apple-touch-icon.png') ?>">
<link rel="icon" type="image/png" sizes="32x32" href="<?php echo $block->getViewFileUrl('Magento_Theme::images/icons/favicon-32x32.png') ?>">
<link rel="icon" type="image/png" sizes="16x16" href="<?php echo $block->getViewFileUrl('Magento_Theme::images/icons/favicon-16x16.png') ?>">
<link rel="manifest" href="<?php echo $block->getViewFileUrl('Magento_Theme::images/icons/site.webmanifest') ?>">
<link rel="mask-icon" href="<?php echo $block->getViewFileUrl('Magento_Theme::images/icons/safari-pinned-tab.svg') ?>" color="#f26322">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">