<?php
	$_helper_store = $this->helper('StudioEmma\Core\Helper\Store');
?>
<meta property="og:locale" content="<?php echo $_helper_store->getLocale()?>" />
<meta property="og:type" content="website" />
<meta property="og:title" content="<?php echo __('This is the general title of the website, if not overwritten by Category or PDP') ?>" />
<meta property="og:image" content="<?php echo $block->getViewFileUrl('Magento_Theme::images/facebook-og-preview.jpg') ?>" />
<meta property="og:image:secure_url" content="<?php echo $block->getViewFileUrl('Magento_Theme::images/facebook-og-preview.jpg') ?>" />
<meta property="og:image:type" content="image/jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="600">
<meta property="og:description" content="<?php echo __('This is the general description of the website, if not overwritten by Category or PDP') ?>" />
<meta property="og:site_name" content="<?php echo $this->getBaseUrl(); ?>" />
<meta property="og:url" content="<?php echo "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]" ?>" />
