<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="colm1-2">
    <div class="colm-grid non-responsive">
        <div class="colm1-2">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-links-col1')->toHtml();?>
        </div>
        <div class="colm1-2">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-links-col2')->toHtml();?>
        </div>
    </div>
</div>