<?php

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<?php switch ($block->getShowPart()):
    case 'welcome': ?>
        <li class="greet welcome" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <div class="c-account-dropdown is-hidden-on-load" data-bind="css: { 'is-hidden-on-load': !customer(), 'is-active': menuActive() }">
                <a href="javascript:void(0)" data-bind="click: toggleMenu">
                    <span data-bind="text: customer().firstname"></span>
                </a>
                <ul>
                    <li>
                        <a href="<?= $block->getUrl('customer/account') ?>">
                            <span><?= __('My account') ?></span>
                        </a>
                    </li>
                    <li>
                        <a href="<?= $block->getUrl('sales/order/history') ?>">
                            <span><?= __('My orders') ?></span>
                        </a>
                    </li>
                    <li>
                        <a href="<?= $block->getUrl('customer/account/logout') ?>">
                            <span><?= __('Sign Out') ?></span>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <a href="<?= $block->getUrl('customer/account') ?>" class="is-hidden-on-load" data-bind="css: { 'is-hidden-on-load': !customer() }">
                <span><?= __('Account') ?></span>
            </a>
            <!-- /ko -->
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <?php break; ?>

    <?php case 'other': ?>
        <?= $block->getChildHtml() ?>
    <?php break; ?>

<?php endswitch; ?>
