<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php if ($block->getCollection()->getSize()): ?>

    <?php if ($block->getUseContainer()): ?>
    <div class="pager">
    <?php endif ?>

        <?php if ($block->getShowAmounts()): ?>
        <p class="toolbar-amount">
            <span class="toolbar-number">
            <?php if ($block->getLastPageNum()>1): ?>
                <?php echo __('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum()) ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?php echo __('%1 Item', $block->getTotalNum()) ?>
            <?php else: ?>
                <?php echo __('%1 Item(s)', $block->getTotalNum()) ?>
            <?php endif; ?>
            </span>
        </p>
        <?php endif ?>

        <?php if ($block->getLastPageNum()>1): ?>
        <div class="pages">
            <strong class="label pages-label" id="paging-label"><?php echo __('Page') ?></strong>
            <ul class="items pages-items hide-xs" aria-labelledby="paging-label">
            <?php if (!$block->isFirstPage()): ?>
                <li class="item pages-item-previous">
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <a class="<?php echo $text ? 'link ' : 'action '?> previous" href="<?php echo $block->getPreviousPageUrl() ?>" title="<?php echo $text ? $text : __('Previous') ?>" rel="prev">
                        <span class="label"><?php echo __('Page') ?></span>
                        <span><?php echo $text ? $text : __('Previous') ?></span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowFirst()): ?>
                <li class="item">
                    <a class="page first" href="<?php echo $block->getFirstPageUrl() ?>">
                        <span class="label"><?php echo __('Page') ?></span>
                        <span>1</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowPreviousJump()): ?>
                <li class="item">
                    <a class="page previous jump" title="" href="<?php echo $block->getPreviousJumpUrl() ?>" rel="prev">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php foreach ($block->getFramePages() as $_page): ?>
                <?php if ($block->isPageCurrent($_page)): ?>
                    <li class="item current">
                        <strong class="page">
                            <span class="label"><?php echo __('You\'re currently reading page') ?></span>
                            <span><?php echo $_page ?></span>
                        </strong>
                    </li>
                <?php else: ?>
                    <li class="item">
                        <a href="<?php echo $block->getPageUrl($_page) ?>" class="page">
                            <span class="label"><?php echo __('Page') ?></span>
                            <span><?php echo $_page ?></span>
                        </a>
                    </li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($block->canShowNextJump()): ?>
                <li class="item">
                    <a class="page next jump" title="" href="<?php echo $block->getNextJumpUrl() ?>" rel="next">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowLast()): ?>
              <li class="item">
                  <a class="page last" href="<?php echo $block->getLastPageUrl() ?>">
                      <span class="label"><?php echo __('Page') ?></span>
                      <span><?php echo $block->getLastPageNum() ?></span>
                  </a>
              </li>
            <?php endif;?>

            <?php if (!$block->isLastPage()): ?>
                <li class="item pages-item-next">
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?php echo $text ? 'link ' : 'action '?> next" href="<?php echo $block->getNextPageUrl() ?>" title="<?php echo $text ? $text : __('Next') ?>" rel="next">
                        <span class="label"><?php echo __('Page') ?></span>
                        <span><?php echo $text ? $text : __('Next') ?></span>
                    </a>
                </li>
            <?php endif;?>
            </ul>

            <div class="mobile-pager show-xs">
                <select onchange="location = this.options[this.selectedIndex].value;">
                    <?php if ($block->canShowFirst()): ?>
                        <option value="<?php echo $block->getFirstPageUrl() ?>"><?php echo __('Page') ?> 1</option>
                    <?php endif;?>

                    <?php foreach ($block->getFramePages() as $_page): ?>
                        <?php if ($block->isPageCurrent($_page)): ?>
                            <option value="<?php echo $_page ?>" selected="selected"><?php echo __('Page') ?> <?php echo $_page ?></option>
                        <?php else: ?>
                            <option value="<?php echo $block->getPageUrl($_page) ?>"><?php echo __('Page') ?> <?php echo $_page ?></option>
                        <?php endif;?>
                    <?php endforeach;?>

                    <?php if ($block->canShowLast()): ?>
                      <option value="<?php echo $block->getLastPageUrl() ?>"><?php echo __('Page') ?> <?php echo $block->getLastPageNum() ?></option>
                    <?php endif;?>
                </select>

                <?php if (!$block->isLastPage()): ?>
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?php echo $text ? 'link ' : 'action '?> next" href="<?php echo $block->getNextPageUrl() ?>" title="<?php echo $text ? $text : __('Next') ?>" rel="next">
                        <span class="label"><?php echo __('Page') ?></span>
                        <span><?php echo $text ? $text : __('Next') ?></span>
                    </a>
                <?php endif;?>

                <?php if (!$block->isFirstPage()): ?>
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <a class="<?php echo $text ? 'link ' : 'action '?> previous" href="<?php echo $block->getPreviousPageUrl() ?>" title="<?php echo $text ? $text : __('Previous') ?>" rel="prev">
                        <span class="label"><?php echo __('Page') ?></span>
                        <span><?php echo $text ? $text : __('Previous') ?></span>
                    </a>
                <?php endif;?>
            </div>

        </div>
        <?php endif; ?>

    <?php if ($block->isShowPerPage()): ?>
        <div class="limiter">
            <strong class="limiter-label"><?php echo __('Show') ?></strong>
            <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                    <option value="<?php echo $block->getLimitUrl($_key) ?>"<?php if ($block->isLimitCurrent($_key)): ?>
                        selected="selected"<?php endif ?>>
                        <?php echo $_limit ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <span class="limiter-text"><?php echo __('per page') ?></span>
        </div>
    <?php endif ?>

    <?php if ($block->getUseContainer()): ?>
    </div>
    <?php endif ?>

<?php endif ?>
