<?php
// See Stores -> Configuration -> Social Media
$scope = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;
if (!empty($block->getConfig()->getValue('socialmediageneral/general/enablefollowlinks', $scope))):
    $channels = array('facebook' => 'Facebook', 'twitter' => 'Twitter', 'instagram' => 'Instagram', 'linkedin' => 'Linkedin', 'youtube' => 'Youtube', 'pinterest' => 'Pinterest', 'googleplus' => 'Google+', 'vimeo' => 'vimeo');
?>
<div class="social">
    <ul>
    <?php foreach ($channels as $channel => $label): ?>
        <?php if (!empty($block->getConfig()->getValue('socialmediachannels/'.$channel.'channel/enable'.$channel.'followlink', $scope)) && !empty($block->getConfig()->getValue('socialmediachannels/'.$channel.'channel/'.$channel.'followlink', $scope))): ?>
        <li>
            <a href="<?= $block->getConfig()->getValue('socialmediachannels/'.$channel.'channel/'.$channel.'followlink', $scope) ?>"
                    title="<?= (!empty($block->getConfig()->getValue('socialmediachannels/'.$channel.'channel/'.$channel.'followlinkalt', $scope))) ? $block->getConfig()->getValue('socialmediachannels/'.$channel.'channel/'.$channel.'followlinkalt', $scope) : sprintf(__('Follow us on %s'), $label) ?>"
                    class="<?= (!empty($block->getConfig()->getValue('socialmediachannels/'.$channel.'channel/'.$channel.'icon', $scope))) ? 'social-custom' : 'social-'.$channel ?>">
                <?php if (!empty($block->getConfig()->getValue('socialmediachannels/'.$channel.'channel/'.$channel.'icon', $scope))): ?>
                <img src="/media/socialmedia/<?= $block->getConfig()->getValue('socialmediachannels/'.$channel.'channel/'.$channel.'icon', $scope) ?>"
                            alt="<?= (!empty($block->getConfig()->getValue('socialmediachannels/'.$channel.'channel/'.$channel.'followlinkalt', $scope))) ? $block->getConfig()->getValue('socialmediachannels/'.$channel.'channel/'.$channel.'followlinkalt', $scope) : sprintf(__('Follow us on %s'), $label) ?>" />
                <?php else: ?>
                    <span>&nbsp;</span>
                <?php endif; ?>
            </a>
        </li>
        <?php endif; ?>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
