<?php

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @see \StudioEmma\Optimus\Block\Html\Topmenu
 */
?>
<?php
    $columnsLimit = $block->getColumnsLimit() ?: 0;
    $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
    $currentUrl = $block->getCurrentUrl();
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 home <?php if($currentUrl == '/'): ?>active<?php endif; ?>"><a href="/" title="<?php echo __('Home') ?>" class="level-top"><span></span></a></li>
        <?php echo $_menu; ?>
    </ul>
</nav>
