<?php
/**
 *  template of simple p element with a class and a translated label inside
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<?php if (!$block->getIsDisabled()): ?>
<p<?php if ($class = $block->getCssClass()):?> class="<?php echo $block->escapeHtml(__($class))?>"<?php endif;?>>
    <?php echo $block->escapeHtml(__($block->getLabel()))?>
</p>
<?php endif; ?>
