<?php
    $_product = $block->getProduct();
    $_productName = urlencode($_product->getName());
    $_productUrl = $_product->getProductUrl();
    // See Stores -> Configuration -> Social Media
    $scope = \Magento\Store\Model\ScopeInterface::SCOPE_STORE;
    if (!empty($block->getConfig()->getValue('socialmediageneral/general/enablesharing', $scope))):
        if (!empty($block->getConfig()->getValue('socialmediageneral/addthis/addthisinstallcode', $scope)) && !empty($block->getConfig()->getValue('socialmediageneral/addthis/addthisinlinesharebuttons', $scope))):
            echo '<div class="social-sharing">';
            echo $block->getConfig()->getValue('socialmediageneral/addthis/addthisinstallcode', $scope);
            echo $block->getConfig()->getValue('socialmediageneral/addthis/addthisinlinesharebuttons', $scope);
            echo '</div>';
        else:
?>
<div class="social-sharing">
    <div class="hover-action-container">
        <a href="javascript:void(0)" title="" class="hover-action"><?=__('Share')?></a>
        <div class="hover-action-content">
            <div class="social">
                <ul>
                    <?php if (!empty($block->getConfig()->getValue('socialmediachannels/facebookchannel/enablefacebooksharing', $scope))): ?>
                    <li>
                        <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $_productUrl; ?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=440,width=600');return false;" title="" class="social-facebook">
                            <span>&nbsp;</span>
                        </a>
                    </li>
                    <?php endif; ?>
                    <?php if (!empty($block->getConfig()->getValue('socialmediachannels/twitterchannel/enabletwittersharing', $scope))): ?>
                    <li>
                        <a href="https://twitter.com/intent/tweet?text=<?php echo $_productName . '+' . $_productUrl; ?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=440,width=600');return false;" title="" class="social-twitter twitter-share-button">
                            <span>&nbsp;</span>
                        </a>
                    </li>
                    <?php endif; ?>
                    <?php if (!empty($block->getConfig()->getValue('socialmediachannels/linkedinchannel/enablelinkedinsharing', $scope))): ?>
                    <li>
                        <a href="https://www.linkedin.com/shareArticle?mini=true&url=<?php echo $_productUrl; ?>&title=<?php echo $_productName ?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=440,width=600');return false;" title="" class="social-linkedin">
                            <span>&nbsp;</span>
                        </a>
                    </li>
                    <?php endif; ?>
                    <?php if (!empty($block->getConfig()->getValue('socialmediachannels/pinterestchannel/enablepinterestsharing', $scope))): ?>
                    <li>
                        <a href="http://pinterest.com/pin/create/button/?url=<?php echo $_productUrl; ?>&media=<?php echo $block->getImage($_product, "product_page_main_image_default")->getImageUrl(); ?>&description=<?php echo $_productName; ?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=440,width=600');return false;" title="" class="social-pinterest">
                            <span>&nbsp;</span>
                        </a>
                    </li>
                    <?php endif; ?>
                    <?php if (!empty($block->getConfig()->getValue('socialmediachannels/googlepluschannel/enablegoogleplussharing', $scope))): ?>
                    <li>
                        <a href="https://plus.google.com/share?url=<?php echo $_productUrl; ?>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=440,width=600');return false;" title="" class="social-googleplus">
                            <span>&nbsp;</span>
                        </a>
                    </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php endif; endif; ?>
