<!-- This template is meant for stock information: be it dynamic or static (CMS block) -->

<?php 
    //Load objectmanager instance
    $manager = Magento\Framework\App\ObjectManager::getInstance();

    //Load block            
    $contentblock = $manager->create('Magento\Cms\Model\Block')->load('product_info_stock');
    //Check to see if block is active
    if($contentblock->isActive()): 
        //If active -> output block
        echo $contentblock->getContent();
    else:
        //If not active -> output static content with outline
        ?>
        <div class="product-info-stock">
            <ul>
                <li>Op voorraad</li>
                <li>Voor 14u besteld, morgen geleverd.</li>
                <li>Slechts €2,95 verzendingskosten (België). Gratis levering vanaf €40!</li>
            </ul>
        </div>
        <?php
    endif;
?>