<!-- This template is meant for stock information: be it dynamic or static (CMS block) -->

<?php 

    //Load block            
    $contentblock = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('product_info_stock')->toHtml();
    //Check to see if block is empty
    if(!empty($contentblock)): 
        //If not empty -> output block
        echo $contentblock;
    else:
        //If empty -> output static content with outline
        ?>
        <div class="product-info-stock">
            <ul>
                <li>Op voorraad</li>
                <li>Voor 14u besteld, morgen geleverd.</li>
                <li>Slechts €2,95 verzendingskosten (België). Gratis levering vanaf €40!</li>
            </ul>
        </div>
        <?php
    endif;
?>