<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Added Availability as Rich snippet to in & out of stock for MASE2OT-5
 * 
 */


?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?php echo __('Availability') ?>">
            <span itemprop="availability" content="InStock"><?php echo __('In stock') ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?php echo __('Availability') ?>">
            <span itemprop="availability" content="OutOfStock"><?php echo __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
