<?php 
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $block->getCurrentCategory();
	$_helper_store = $this->helper('StudioEmma\Core\Helper\Store');
?>
<meta property="og:locale" content="<?php echo $_helper_store->getLocale()?>" />
<meta property="og:type" content="product.group" />
<?php if ($_name = $block->getCurrentCategory()->getName()): ?>
    <meta property="og:title" content="<?php echo strip_tags($this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_name, 'name')) ?>" />
<?php endif; ?>
<meta property="og:image" content="<?php echo $block->getViewFileUrl('Magento_Theme::images/facebook-og-preview.jpg') ?>" />
<meta property="og:image:secure_url" content="<?php echo $block->getViewFileUrl('Magento_Theme::images/facebook-og-preview.jpg') ?>" />
<meta property="og:image:type" content="image/jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="600">
<?php if ($_description = $block->getCurrentCategory()->getDescription()): ?>
    <meta property="og:description" content="<?php echo strip_tags($this->helper('Magento\Catalog\Helper\Output')->categoryAttribute($block->getCurrentCategory(), $_description, 'description')) ?>" />
<?php endif; ?>
<meta property="og:site_name" content="<?php echo $this->getBaseUrl(); ?>" />
<meta property="og:url" content="<?php echo "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]" ?>" />