<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */

$argNoFollow = $block->getNoFollow();
if($block->getVar('layerednav_expand_active')){
    $nofItemsShown = $block->getVar('layerednav_items_shown');
}else{
    //Collapsing inactive
    $nofItemsShown = 0;
}

?>
<?php if($nofItemsShown > 0): ?>
<ol class="items is-expandable">
<?php else: ?>
<ol class="items">
<?php endif; ?>
    <?php 
    $i = 0;
    foreach ($filterItems as $filterItem):
    $i++; ?>
        <?php if($i > $nofItemsShown && $nofItemsShown != 0): ?>
        <li class="item extra-options">
        <?php else: ?>
        <li class="item">
        <?php endif; ?>
            <?php if ($filterItem->getCount() > 0): ?>
                <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"<?php if($argNoFollow): ?> rel="nofollow"<?php endif; ?>>
                    <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?= /* @escapeNotVerified */ __('item') ?><?php else:?> <?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount() ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?= /* @escapeNotVerified */ __('item') ?><?php else:?><?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
    <?php if($nofItemsShown > 0 && $i > $nofItemsShown): ?>
        <li class="more"><a href="#" class="js-toggle-hidden-layerednav"><span class="more"><?php echo __('More') ?></span><span class="less"><?php echo __('Less') ?></span></a></li>
    <?php endif; ?>
</ol>
