<?php
/**
 * Category listing template
 * Copyright © Studio Emma. All rights reserved.
 *
 * Usage in a cms block or page
 *
 * {{block class="StudioEmma\Optimus\Block\Navigation" template="Magento_Catalog::navigation/category-listing.phtml" title="Lorem ipsum" column_count="4" selected_parent_category_id="3"}}
 *
 * {{block class="StudioEmma\Optimus\Block\Navigation" template="Magento_Catalog::navigation/category-listing.phtml" title="Lorem ipsum" column_count="3" selected_category_ids="3,4,5" }}
 *
 *
 */

$categories = $this->getCategories();

if ($this->categoriesCount() > 0):

    if (!empty($this->getCssClass())): ?>
        <div class="<?= $this->getCssClass() ?>">
    <?php endif; ?>
        <?php if (!empty($block->getTitle())): ?>
            <h2><?= $block->getTitle(); ?></h2>
        <?php endif; ?>
            <nav role="navigation">
            <?php if ($this->bShowColumns()): ?>
                <div class="colm-grid">
                    <div class="colm colm1-<?= $this->columnCount()?>">
            <?php endif; ?>
                        <ul class="catalog-navigation">
                    <?php $k = 0;
                    for ($i = 0; $i < $this->categoriesCount(); $i++):
                        if (isset($categories[$i])):
                            $k++;
                    ?>
                            <li class='category category-<?= $categories[$i]->getId(); ?>'>
                                <a class="category-link" href="<?= $categories[$i]->getUrl() ?>" title="<?= $this->escapeHtml($categories[$i]->getName()) ?>">
                                    <span><?= $this->escapeHtml($categories[$i]->getName()) ?></span>
                                </a>
                            </li>
                        <?php
                            if ($k == $this->nofItemsPerColumn() && $i != ($this->categoriesCount() - 1) && $this->bShowColumns()):
                                $k = 0;
                        ?>
                        </ul>
                    </div>
                    <div class="colm colm1-<?= $this->columnCount() ?>">
                        <ul class="catalog-navigation">
                        <?php
                            endif;
                        endif;
                    endfor; ?>
                        </ul>
                <?php if ($this->bShowColumns()): ?>
                    </div>
                </div>
                <?php endif; ?>
            </nav>
    <?php if (!empty($this->getCssClass())): ?>
        </div>
    <?php endif; ?>

<?php endif; ?>
